from __future__ import annotations

import pi_ai

EXPECTED_EXPORTS = {
    "AssistantContent",
    "AssistantMessage",
    "AssistantMessageDiagnostic",
    "AssistantMessageEvent",
    "AssistantMessageStartEvent",
    "AssistantStream",
    "Context",
    "CredentialResolver",
    "DeferredHandle",
    "DiagnosticErrorInfo",
    "DoneEvent",
    "ErrorEvent",
    "FakeProvider",
    "ImageContent",
    "JsonObject",
    "JsonValue",
    "Message",
    "Model",
    "ModelCost",
    "ModelCostRates",
    "ModelCostTier",
    "ModelInput",
    "ModelThinkingLevel",
    "Provider",
    "StopReason",
    "StreamConsumedError",
    "StreamFunction",
    "StreamOptions",
    "StreamProtocolError",
    "TextContent",
    "TextDeltaEvent",
    "TextEndEvent",
    "TextStartEvent",
    "ThinkingContent",
    "ThinkingDeltaEvent",
    "ThinkingEndEvent",
    "ThinkingLevel",
    "ThinkingStartEvent",
    "Tool",
    "ToolCall",
    "ToolCallDeltaEvent",
    "ToolCallEndEvent",
    "ToolCallStartEvent",
    "ToolResultContent",
    "ToolResultMessage",
    "UnknownToolError",
    "Usage",
    "UsageCost",
    "UserContent",
    "UserMessage",
    "__version__",
    "clamp_thinking_level",
    "create_assistant_stream",
    "decode_event_json",
    "decode_message_json",
    "encode_event_json",
    "encode_message_json",
    "encode_tool_json",
    "event_json_schema",
    "fake_assistant_message",
    "fake_model",
    "get_supported_thinking_levels",
    "message_json_schema",
    "models_are_equal",
    "tool_json_schema",
    "validate_model_thinking_level",
    "validate_thinking_level",
    "validate_tool_arguments",
    "validate_tool_call",
}


def test_pi_ai_public_exports_are_explicit_and_stable() -> None:
    assert set(pi_ai.__all__) == EXPECTED_EXPORTS
    for name in EXPECTED_EXPORTS:
        assert hasattr(pi_ai, name), name
