"""Provider boundary for the Pi Python distribution."""

from importlib.metadata import version as _distribution_version

from .context import Context
from .events import (
    AssistantMessageEvent,
    AssistantMessageStartEvent,
    DoneEvent,
    ErrorEvent,
    TextDeltaEvent,
    TextEndEvent,
    TextStartEvent,
    ThinkingDeltaEvent,
    ThinkingEndEvent,
    ThinkingStartEvent,
    ToolCallDeltaEvent,
    ToolCallEndEvent,
    ToolCallStartEvent,
)
from .messages import (
    AssistantContent,
    AssistantMessage,
    AssistantMessageDiagnostic,
    DeferredHandle,
    DiagnosticErrorInfo,
    ImageContent,
    JsonObject,
    JsonValue,
    Message,
    StopReason,
    TextContent,
    ThinkingContent,
    ToolCall,
    ToolResultContent,
    ToolResultMessage,
    UserContent,
    UserMessage,
)
from .models import (
    Model,
    ModelCost,
    ModelCostRates,
    ModelCostTier,
    ModelInput,
    clamp_thinking_level,
    get_supported_thinking_levels,
    models_are_equal,
)
from .provider import CredentialResolver, Provider, StreamFunction, StreamOptions
from .stream import (
    AssistantStream,
    StreamConsumedError,
    StreamProtocolError,
    create_assistant_stream,
)
from .testing import FakeProvider, fake_assistant_message, fake_model
from .tools import Tool, UnknownToolError, validate_tool_arguments, validate_tool_call
from .usage import (
    ModelThinkingLevel,
    ThinkingLevel,
    Usage,
    UsageCost,
    validate_model_thinking_level,
    validate_thinking_level,
)
from .wire.codec import (
    decode_event_json,
    decode_message_json,
    encode_event_json,
    encode_message_json,
    encode_tool_json,
    event_json_schema,
    message_json_schema,
    tool_json_schema,
)

__version__ = _distribution_version("pi-python")

__all__ = [
    "AssistantContent",
    "AssistantMessage",
    "AssistantMessageDiagnostic",
    "AssistantMessageEvent",
    "AssistantMessageStartEvent",
    "AssistantStream",
    "Context",
    "CredentialResolver",
    "DeferredHandle",
    "DiagnosticErrorInfo",
    "DoneEvent",
    "ErrorEvent",
    "FakeProvider",
    "ImageContent",
    "JsonObject",
    "JsonValue",
    "Message",
    "Model",
    "ModelCost",
    "ModelCostRates",
    "ModelCostTier",
    "ModelInput",
    "ModelThinkingLevel",
    "Provider",
    "StopReason",
    "StreamConsumedError",
    "StreamFunction",
    "StreamOptions",
    "StreamProtocolError",
    "TextContent",
    "TextDeltaEvent",
    "TextEndEvent",
    "TextStartEvent",
    "ThinkingContent",
    "ThinkingDeltaEvent",
    "ThinkingEndEvent",
    "ThinkingLevel",
    "ThinkingStartEvent",
    "Tool",
    "ToolCall",
    "ToolCallDeltaEvent",
    "ToolCallEndEvent",
    "ToolCallStartEvent",
    "ToolResultContent",
    "ToolResultMessage",
    "UnknownToolError",
    "Usage",
    "UsageCost",
    "UserContent",
    "UserMessage",
    "__version__",
    "clamp_thinking_level",
    "create_assistant_stream",
    "decode_event_json",
    "decode_message_json",
    "encode_event_json",
    "encode_message_json",
    "encode_tool_json",
    "event_json_schema",
    "fake_assistant_message",
    "fake_model",
    "get_supported_thinking_levels",
    "message_json_schema",
    "models_are_equal",
    "tool_json_schema",
    "validate_model_thinking_level",
    "validate_thinking_level",
    "validate_tool_arguments",
    "validate_tool_call",
]
