"""Python extension surface for the coding agent."""

from .api import ExtensionAPI
from .auth_api import CredentialStore, CredentialStoreUnavailableError, ExtensionAuthApi
from .events import (
    AgentSettledEvent,
    BeforeProviderHeadersEvent,
    BeforeProviderRequestEvent,
    ContextEvent,
    ContextEventResult,
    ExtensionAgentEndEvent,
    ExtensionAgentStartEvent,
    ExtensionLifecycleEvent,
    ExtensionMessageEndEvent,
    ExtensionMessageStartEvent,
    ExtensionMessageUpdateEvent,
    ExtensionToolExecutionEndEvent,
    ExtensionToolExecutionStartEvent,
    ExtensionToolExecutionUpdateEvent,
    ExtensionTurnEndEvent,
    ExtensionTurnStartEvent,
    ToolCallEvent,
    ToolCallEventResult,
    ToolResultEvent,
    UiPromptEndEvent,
    UiPromptStartEvent,
)
from .hooks import HookOutcome, HookRunner, invoke_hook
from .lifecycle import ExtensionLifecycle, LifecycleClosedError, TeardownToken
from .loader import (
    ExtensionIdentity,
    ExtensionLoader,
    ExtensionNotTrustedError,
    discover_extensions,
)
from .metadata import ExtensionManifestError, ExtensionMetadata, read_manifest
from .registry import (
    CapabilityRegistry,
    FlagState,
    Registration,
    RegistryConflictError,
    RegistryError,
    RegistryInvalidNameError,
)
from .runtime import DefaultExtensionRuntime
from .session_context import (
    ExtensionSessionEvent,
    SessionBeforeCompactEvent,
    SessionBeforeForkEvent,
    SessionBeforeSwitchEvent,
    SessionBeforeTreeEvent,
    SessionCompactEvent,
    SessionShutdownEvent,
    SessionStartEvent,
    SessionTreeEvent,
    TreePreparation,
)
from .ui_api import ExtensionUiApi, UiBridge, UiUnavailableError

__all__ = [
    "AgentSettledEvent",
    "BeforeProviderHeadersEvent",
    "BeforeProviderRequestEvent",
    "CapabilityRegistry",
    "CredentialStore",
    "CredentialStoreUnavailableError",
    "ContextEvent",
    "ContextEventResult",
    "DefaultExtensionRuntime",
    "ExtensionAgentEndEvent",
    "ExtensionAgentStartEvent",
    "ExtensionAPI",
    "ExtensionAuthApi",
    "ExtensionIdentity",
    "ExtensionLifecycle",
    "ExtensionLifecycleEvent",
    "ExtensionLoader",
    "ExtensionManifestError",
    "ExtensionMetadata",
    "ExtensionMessageEndEvent",
    "ExtensionMessageStartEvent",
    "ExtensionMessageUpdateEvent",
    "ExtensionToolExecutionEndEvent",
    "ExtensionToolExecutionStartEvent",
    "ExtensionToolExecutionUpdateEvent",
    "ExtensionNotTrustedError",
    "ExtensionSessionEvent",
    "ExtensionTurnEndEvent",
    "ExtensionTurnStartEvent",
    "ExtensionUiApi",
    "FlagState",
    "HookOutcome",
    "HookRunner",
    "LifecycleClosedError",
    "Registration",
    "RegistryConflictError",
    "RegistryError",
    "RegistryInvalidNameError",
    "SessionBeforeCompactEvent",
    "SessionBeforeForkEvent",
    "SessionBeforeSwitchEvent",
    "SessionBeforeTreeEvent",
    "SessionCompactEvent",
    "SessionShutdownEvent",
    "SessionStartEvent",
    "SessionTreeEvent",
    "TeardownToken",
    "ToolCallEvent",
    "ToolCallEventResult",
    "ToolResultEvent",
    "TreePreparation",
    "UiBridge",
    "UiPromptEndEvent",
    "UiPromptStartEvent",
    "UiUnavailableError",
    "discover_extensions",
    "invoke_hook",
    "read_manifest",
]
